# Generated by Django 5.1.6 on 2025-03-16 03:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0011_alter_thread_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
