# Generated by Django 5.1.6 on 2025-03-16 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0013_thread_is_technical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='tradeapp.offer'),
        ),
    ]
