# Generated by Django 5.1.7 on 2025-03-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0016_message_is_restricted_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_post_messages',
            field=models.BooleanField(default=True),
        ),
    ]
