# Generated by Django 5.2.6 on 2025-09-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tradeapp", "0018_verificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
